# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # - errcheck # fmt.Fprintlnのエラーチェックが多すぎるため無効化
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    # - funlen # 長い関数は必要に応じて許可
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # fmt.Print系は除外
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - (os.File).Close

  gocyclo:
    min-complexity: 15

  funlen:
    lines: 150
    statements: 80

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  dupl:
    threshold: 150

  gosec:
    severity: medium
    confidence: medium

  lll:
    line-length: 140

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments

issues:
  exclude-dirs-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - goconst
        - gosec
        - lll

    - path: cmd/
      linters:
        - funlen

  exclude:
    # fmt.Print系のエラーは無視
    - Error return value of `fmt\.(Fprint|Fprintf|Fprintln|Print|Printf|Println)` is not checked
    # defer closeのエラーは無視
    - Error return value of `.*\.Close` is not checked
    # os.Stderr/Stdoutへの書き込みエラーは無視
    - Error return value of .((os\.)?std(out|err)\..*|.*Flush|os\.Remove(All)?|os\.(Un)?Setenv). is not checked