name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['1.24']
        include:
          - os: ubuntu-latest
            output: conreq-linux-amd64
          - os: windows-latest
            output: conreq-windows-amd64.exe
          - os: macos-latest
            output: conreq-darwin-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: ${{ matrix.go }}

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: |
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        go build -v -ldflags="-s -w -X main.version=${{ github.sha }} -X main.date=${BUILD_DATE}" -o ${{ matrix.output }} cmd/conreq/main.go

    - name: Test binary
      run: |
        ./${{ matrix.output }} --version

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: conreq-${{ matrix.os }}
        path: ${{ matrix.output }}

  cross-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod download

    - name: Cross compile
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o conreq-linux-amd64 cmd/conreq/main.go
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o conreq-linux-arm64 cmd/conreq/main.go
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o conreq-darwin-amd64 cmd/conreq/main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o conreq-darwin-arm64 cmd/conreq/main.go
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o conreq-windows-amd64.exe cmd/conreq/main.go
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o conreq-windows-arm64.exe cmd/conreq/main.go

    - name: Upload cross-compiled binaries
      uses: actions/upload-artifact@v4
      with:
        name: conreq-all-platforms
        path: conreq-*